### ISSUE TITLE
linter: vscode extension burning my CPU because of node_modules

### ISSUE THREAD

**Issue by Mathis-6** [oxc-project/oxc#17306]
### What version of Oxlint are you using?

not sure

### What does your `.oxlintrc.json` config file look like?

i don't have one.

### What happened?

I noticed that after starting VSCode, my CPU still burns for 5 minutes after.
The process "oxc_language_server --lsp" is using half a CPU core, and ~5 mbps of network usage (my workspace is on a SMB drive). Until then i can't use the linter for working in JS projects.

When checking the activity with wireshark, it seems oxc is doing things under the "node_modules" directories.

<img width="1139" height="470" alt="Image" src="https://github.com/user-attachments/assets/57b0ee2c-3c6e-4bad-9d91-1332c79b6d05" />

This is the startup performances : 
```md
## Extension Activation Stats

| Extension                         | Eager | Load Code | Call Activate | Finish Activate | Event                          | By                                |
| --------------------------------- | ----- | --------- | ------------- | --------------- | ------------------------------ | --------------------------------- |
| vscode.git                        | true  | 225       | 7             | 1596            | *                              | vscode.git                        |
| vscode.git-base                   | true  | 14        | 2             | 0               | *                              | vscode.git                        |
| vscode.configuration-editing      | false | 84        | 17            | 0               | onLanguage:jsonc               | vscode.configuration-editing      |
| vscode.emmet                      | false | 42        | 57            | 0               | onLanguage                     | vscode.emmet                      |
| vscode.extension-editing          | false | 70        | 1             | 0               | onLanguage:markdown            | vscode.extension-editing          |
| vscode.github-authentication      | false | 112       | 7             | 17              | onAuthenticationRequest:github | vscode.github-authentication      |
| vscode.json-language-features     | false | 771       | 1             | 966             | onLanguage:jsonc               | vscode.json-language-features     |
| vscode.markdown-language-features | false | 323       | 17            | 618             | onLanguage:markdown            | vscode.markdown-language-features |
| vscode.markdown-math              | false | 21        | 0             | 0               | api                            | vscode.markdown-language-features |
| vscode.merge-conflict             | false | 59        | 12            | 11              | onStartupFinished              | vscode.merge-conflict             |
| oxc.oxc-vscode                    | false | 120       | 3             | 293950          | onLanguage:javascript          | oxc.oxc-vscode                    |
```

**Comment by camc314** [comment]
Hi, what version of the extension are you using? We fixed an issue https://github.com/oxc-project/oxc/commit/dd357304ef2eae89a3982554a5b447153679cb80, that sounds like what you're experiencing

**Comment by camc314** [comment]
Can you also share your oxlint config? Are you using type aware linting?

**Comment by connorshea** [comment]
I wonder if the problem is potentially due to this chunk of code in [`tsgolint.rs`](https://github.com/oxc-project/oxc/blob/3e778fb64f971217cc3dddf73969c785bb9ca802/crates/oxc_linter/src/tsgolint.rs):

```rs
    // Finally, search in the system PATH
    // This supports package managers that install binaries globally and make them
    // available via PATH
    if let Ok(path_env) = std::env::var("PATH") {
        for dir in std::env::split_paths(&path_env) {
            for file in files {
                let candidate = dir.join(file);
                if candidate.is_file() {
                    return Ok(candidate);
                }
            }
        }
    }
```

If it can't find any other options and falls back to this, it could end up doing wacky things if you have a lot in your `PATH` env var. Especially over a networked drive.

**Comment by Mathis-6** [comment]
The ripgrep bug is still happening in oxc 1.36.0, but now the oxc language server don't start at all.
In vscode it shows this error after 2 minutes

<img width="209" height="170" alt="Image" src="https://github.com/user-attachments/assets/c6b51df4-dce0-498e-96ea-c79429cb1f26" />

**Comment by Mathis-6** [comment]
I think the oxlint and oxfmt binaries should be bundled with the extension ? Or i need to download them separately ?
